In [5]:
import numpy as np

def gauss_jordan_inverse(A):
    n = A.shape[0]
    AI = np.hstack([A.astype(float), np.eye(n)])
    for i in range(n):
        pivot = AI[i, i]
        if pivot == 0:
            for k in range(i+1, n):
                if AI[k, i] != 0:
                    AI[[i, k]] = AI[[k, i]]
                    pivot = AI[i, i]
                    break
        AI[i] = AI[i] / pivot
        for j in range(n):
            if j != i:
                AI[j] = AI[j] - AI[j, i] * AI[i]
    return AI[:, n:]

# Ejercicio 1
A1 = np.array([[2, -3], [-1, 1]])
print('Inversa de A1:')
print(gauss_jordan_inverse(A1))

# Ejercicio 2
A2 = np.array([[4, 0, 0, 5], [1, 0, 4, 0], [3, 4, 1, 3], [1, 3, 3, 0]])
print('Inversa de A2:')
print(gauss_jordan_inverse(A2))

Inversa de A1:
[[-1. -3.]
 [-1. -2.]]
Inversa de A2:
[[-36.  45.  60. -80.]
 [  3.  -4.  -5.   7.]
 [  9. -11. -15.  20.]
 [ 29. -36. -48.  64.]]
